services:
  postgres:
    image: postgres:17-alpine
    container_name: work_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    name: spring-jdbc-pgdata